version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flying-cup
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./repos:/app/repos
      - ./config.yaml:/app/config.yaml:ro
